# ------------------------------------------------------------
# weather-test.shaneburkhardt.com
# ------------------------------------------------------------



map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "192.168.2.113";
  set $port$port           8080;

  listen 80;
listen [::]:80;

listen 443 ssl;
listen [::]:443 ssl;


  server_name weather-test.shaneburkhardt.com;

  http2 on;


  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-cache.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-1/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-1/privkey.pem;






  # Block Exploits
  include conf.d/include/block-exploits.conf;







    # Force SSL
    
    set $trust_forwarded_proto "F";
    
    include conf.d/include/force-ssl.conf;





  access_log /data/logs/proxy-host-15_access.log proxy;
  error_log /data/logs/proxy-host-15_error.log warn;

location /sse {
  proxy_pass http://192.168.2.113:8080/sse;
  proxy_buffering off;
  proxy_cache off;
  proxy_read_timeout 86400s;
  proxy_set_header Connection "";
  chunked_transfer_encoding off;
}





  location / {


    

    # Access Rules: 9 total
    
    allow 192.168.1.0/24;
    
    allow 192.168.2.0/24;
    
    allow 192.168.3.0/24;
    
    allow fddd:d91b:1b46:1::/64;
    
    allow fddd:d91b:1b46:2::/64;
    
    allow fddd:d91b:1b46:3::/64;
    
    allow 2603:8001:e83f:b901::/64;
    
    allow 2603:8001:e83f:b902::/64;
    
    allow 2603:8001:e83f:b903::/64;
    
    deny all;

    # Access checks must...
    
    satisfy all;
    








    

    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
