"""selftest.py — known-answer self-test for the energy-ledger scripts (DOC-W.4 / plan C12).

Pinned value: Hs = 0.6500 m, cited from scratch/NOTES-E1E2-RESULTS.md line 84
(E8c KAT): "uniform boundary Hs=0.650 (Tp 14s, from-197, cos^56), islands wetted, wind
zeroed, physics-off, single STAT solve. Round-trip verified 0.6500 all 22 files."

The fixture (fixtures/uniform_hs065.txt) is NOT a copy of E8c's actual production
boundary file — that file (a full 34-freq x 72-dir CIRCLE grid generated by a script
that lives only on librewxr) is not available locally. Instead this is a small
synthetic single-bin SWAN 2D spectral file, engineered so that ledger.py's own
integration functions (freq_widths log-spacing law + integrate()) recover exactly the
already-pinned 0.6500 value. This verifies the ledger integrator's correctness
(log-df spacing, band assignment, Hs = 4*sqrt(m0)) against a documented known-good
total — it does not re-derive a new expected value.

Band-edge assertion: per docs/planning/MARINE-MODEL-EVOLUTION-PLAN-2026-08-15.md
"## NAMED CONSTANTS", the bands are < 0.09 Hz (>11s), 0.09-0.2 Hz (5-11s), > 0.2 Hz
(<5s) -- matching ledger.py's BANDS = [(0.0, 0.09), (0.09, 0.2), (0.2, 99.0)]. The
fixture's single non-zero bin sits at f=0.07208 Hz, i.e. inside the <0.09 Hz band, so
a correct integrator must report ALL of m0 in band 1 and exactly zero in bands 2/3.
This catches band-edge drift, not just integrator/Hs drift.

Hand-derived construction arithmetic (independent of calling ledger.py, so a human can
check it, and so any disagreement with ledger.py's own freq_widths() at construction
time is itself a finding about the script -- see note at bottom):
  5-bin log frequency grid, f0=0.03 Hz, f4=1.0 Hz:
    r = (f4/f0)^(1/4) = (1.0/0.03)^0.25 = 2.40266...
    freqs = [0.03, 0.03*r, 0.03*r^2, 0.03*r^3, 0.03*r^4]
          = [0.03, 0.07208434242404263, 0.17320508075688773,
             0.4161791450287817, 1.0]
  Per-bin df at the chosen bin (freq index 1), geometric bin-edge width:
    sr = sqrt(r) = 1.55003...
    df[1] = freqs[1] * (sr - 1/sr) = 0.07208434242404263 * 0.90499...
          = 0.06523495825223978
  8-bin uniform direction grid, 45 deg spacing -> dtheta = 360/8 = 45.0
  Target m0 for pinned Hs=0.6500 (Hs = 4*sqrt(m0)):
    m0 = (0.6500 / 4)^2 = 0.026406250000000003
  Density value placed at [freq idx 1, dir idx 4] to hit that m0 exactly:
    v = m0 / (dtheta * df[1]) = 0.026406250000000003 / (45.0 * 0.06523495825223978)
      = 0.008995262222543205

  This hand arithmetic was checked at construction time against ledger.py's own
  freq_widths() output and matched to full float precision (both give
  df[1] = 0.06523495825223978, m0 = 0.026406250000000003, Hs = 0.65 exactly) --
  no disagreement found, so no STOP/report was triggered.

Usage:
    python scripts/analysis/selftest.py
    EXPECTED_HS_OVERRIDE=0.9 python scripts/analysis/selftest.py   # local-only perturbation drill
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ledger  # noqa: E402

FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "uniform_hs065.txt")

# Pinned value -- scratch/NOTES-E1E2-RESULTS.md:84 ("Round-trip verified 0.6500 all 22 files").
PINNED_HS = 0.6500
TOLERANCE = 0.0005  # float round-trip only; fixture is engineered to hit PINNED_HS exactly.


def main():
    expected_hs = float(os.environ.get("EXPECTED_HS_OVERRIDE", PINNED_HS))

    with open(FIXTURE) as fh:
        locs, freqs, dirs = ledger.parse_header(fh)
        dfs = ledger.freq_widths(freqs)
        dtheta = 360.0 / len(dirs)
        nf, nd = len(freqs), len(dirs)
        fh.readline()  # date line
        blk = ledger.read_block(fh, nf, nd)
        m0, mb = ledger.integrate(blk, freqs, dfs, dtheta)

    computed_hs = ledger.hs(m0)
    band1_hs = ledger.hs(mb[0])
    band2, band3 = mb[1], mb[2]

    ok = True
    print("computed Hs = %.6f, expected Hs = %.6f (tolerance %.4f)" % (computed_hs, expected_hs, TOLERANCE))
    if abs(computed_hs - expected_hs) > TOLERANCE:
        ok = False

    print("computed band1 (<0.09 Hz) Hs = %.6f, expected == total Hs (%.6f)" % (band1_hs, computed_hs))
    if abs(mb[0] - m0) > 1e-12:
        ok = False
        print("MISMATCH: band1 energy != total m0 (%.12f vs %.12f)" % (mb[0], m0))

    print("computed band2 (0.09-0.2 Hz) energy = %.12f, expected 0.0 exactly" % band2)
    if band2 != 0.0:
        ok = False
        print("MISMATCH: band2 energy is not exactly zero")

    print("computed band3 (>0.2 Hz) energy = %.12f, expected 0.0 exactly" % band3)
    if band3 != 0.0:
        ok = False
        print("MISMATCH: band3 energy is not exactly zero")

    if ok:
        print("PASS")
        return 0
    else:
        print("FAIL")
        return 1


if __name__ == "__main__":
    sys.exit(main())
